Repository wavesplatform/matcher, pull requests merged in 2019-11, with the labels that each got.

#85 DEX-364 Rates error handling
  dex-it/src/test/scala/com/wavesplatform/it/sync/RatesTestSuite.scala
  dex/src/main/scala/com/wavesplatform/dex/api/MatcherApiRoute.scala
  dex/src/main/scala/com/wavesplatform/dex/api/MatcherResponse.scala
  dex/src/main/scala/com/wavesplatform/dex/error/MatcherError.scala
  dex/src/test/scala/com/wavesplatform/dex/api/MatcherApiRouteSpec.scala
Labels: enhancement, version-1.0.x

#89 DEX-459 Node version updated to 1.1.5
  build.sbt
Labels: enhancement, version-1.0.x

#88 DEX-390 Async interaction in it-tests
  dex-it-tools/src/main/scala/com/wavesplatform/dex/it/api/NodeApi.scala
  dex-it-tools/src/main/scala/com/wavesplatform/dex/it/docker/Docker.scala
  dex-it-tools/src/main/scala/com/wavesplatform/dex/it/fp/CanExtract.scala
  dex-it-tools/src/main/scala/com/wavesplatform/dex/it/fp/CanExtractInstances.scala
  dex-it-tools/src/main/scala/com/wavesplatform/dex/it/sttp/LoggingSttpBackend.scala
  dex-it-tools/src/main/scala/com/wavesplatform/dex/it/sttp/SttpBackendOps.scala
  dex-it-tools/src/main/scala/com/wavesplatform/dex/it/waves/MkWavesEntities.scala
  dex-it/src/test/scala/com/wavesplatform/it/MatcherSuiteBase.scala
  dex-it/src/test/scala/com/wavesplatform/it/api/DexApi.scala
  dex-it/src/test/scala/com/wavesplatform/it/api/DexApiOps.scala
  dex-it/src/test/scala/com/wavesplatform/it/api/dex/AssetDecimalsInfo.scala
  dex-it/src/test/scala/com/wavesplatform/it/async/CorrectStatusAfterPlaceTestSuite.scala
  dex-it/src/test/scala/com/wavesplatform/it/it.scala
  dex-it/src/test/scala/com/wavesplatform/it/sync/MatcherRecoveryTestSuite.scala
  dex-it/src/test/scala/com/wavesplatform/it/sync/MultipleMatchersTestSuite.scala
  dex/src/main/scala/com/wavesplatform/dex/AddressActor.scala
  dex/src/main/scala/com/wavesplatform/dex/AssetPairBuilder.scala
  dex/src/main/scala/com/wavesplatform/dex/Matcher.scala
  dex/src/main/scala/com/wavesplatform/dex/caches/AssetDecimalsCache.scala
  dex/src/main/scala/com/wavesplatform/dex/db/AssetsDB.scala
  dex/src/main/scala/com/wavesplatform/dex/settings/MatcherSettings.scala
  project/Dependencies.scala
  waves-integration/src/main/scala/com/wavesplatform/dex/grpc/integration/clients/async/WavesBlockchainAsyncClient.scala
  waves-integration/src/main/scala/com/wavesplatform/dex/grpc/integration/clients/async/WavesBlockchainCachingClient.scala
  waves-integration/src/main/scala/com/wavesplatform/dex/grpc/integration/dto/BriefAssetDescription.scala
Labels: wip

#91 DEX-461 Custom database for the Order History
  dex-it/src/test/resources/order-history/init-user-db.sh
  dex-it/src/test/scala/com/wavesplatform/it/DockerContainerLauncher.scala
  dex-it/src/test/scala/com/wavesplatform/it/sync/OrderHistoryTestSuite.scala
  dex/src/main/resources/application.conf
  dex/src/main/scala/com/wavesplatform/dex/settings/PostgresConnection.scala
Labels: enhancement, version-1.0.x

#94 DEX-378 Errors formatting fixes
  dex-it/src/test/scala/com/wavesplatform/it/sync/OrderRestrictionsTestSuite.scala
  dex/src/main/scala/com/wavesplatform/dex/api/MatcherApiRoute.scala
  dex/src/main/scala/com/wavesplatform/dex/api/MatcherResponse.scala
  dex/src/main/scala/com/wavesplatform/dex/error/Implicits.scala
  dex/src/main/scala/com/wavesplatform/dex/error/MatcherError.scala
  dex/src/main/scala/com/wavesplatform/dex/history/DBRecords.scala
  dex/src/main/scala/com/wavesplatform/dex/history/HistoryRouter.scala
  dex/src/main/scala/com/wavesplatform/dex/meta/Sample.scala
  dex/src/main/scala/com/wavesplatform/dex/model/MatcherModel.scala
  dex/src/main/scala/com/wavesplatform/dex/model/OrderBookResult.scala
  dex/src/main/scala/com/wavesplatform/dex/settings/MatchingRule.scala
  dex/src/main/scala/com/wavesplatform/dex/settings/package.scala
  dex/src/test/scala/com/wavesplatform/dex/MatcherTestData.scala
  dex/src/test/scala/com/wavesplatform/dex/api/MatcherApiRouteSpec.scala
  dex/src/test/scala/com/wavesplatform/dex/history/HistoryRouterSpecification.scala
  dex/src/test/scala/com/wavesplatform/dex/market/OrderBookActorSpecification.scala
Labels: enhancement

#95 DEX-401 Custom further processing of the loading results in gRPC caches
  build.sbt
  dex/build.sbt
  waves-integration/src/main/scala/com/wavesplatform/dex/grpc/integration/caches/AssetDescriptionsCache.scala
  waves-integration/src/main/scala/com/wavesplatform/dex/grpc/integration/caches/BalancesCache.scala
  waves-integration/src/main/scala/com/wavesplatform/dex/grpc/integration/caches/BlockchainCache.scala
  waves-integration/src/main/scala/com/wavesplatform/dex/grpc/integration/caches/FeaturesCache.scala
  waves-integration/src/main/scala/com/wavesplatform/dex/grpc/integration/clients/async/WavesBlockchainCachingClient.scala
  waves-integration/src/test/scala/com/wavesplatform/dex/grpc/integration/caches/BlockchainCacheSpecification.scala
Labels: enhancement

#103 DEX-469 New installation instructions
  .gitignore
  README.md
  dex-it/src/test/resources/nodes/dex-1.conf
  dex-it/src/test/resources/nodes/dex-2.conf
  dex/build.sbt
  dex/dex-devnet.conf
  dex/dex-mainnet.conf
  dex/dex-stagenet.conf
  dex/dex-testnet.conf
  dex/src/main/container/start.sh
  dex/src/main/package/samples/devnet.conf
  dex/src/main/package/samples/mainnet.conf
  dex/src/main/package/samples/stagenet.conf
  dex/src/main/package/samples/testnet.conf
  dex/src/main/resources/application.conf
  dex/src/main/scala/com/wavesplatform/dex/Matcher.scala
  dex/src/main/scala/com/wavesplatform/dex/MatcherSnapshotStore.scala
  dex/src/main/scala/com/wavesplatform/dex/WavesDexCli.scala
  dex/src/main/scala/com/wavesplatform/dex/doc/DocGeneratorApp.scala
  dex/src/main/scala/com/wavesplatform/dex/doc/MatcherErrorDoc.scala
  dex/src/main/scala/com/wavesplatform/dex/model/EventSerializers.scala
  dex/src/main/scala/com/wavesplatform/dex/settings/MatcherSettings.scala
  dex/src/test/resources/application.conf
  dex/src/test/scala/com/wavesplatform/dex/MatcherSnapshotStoreSpec.scala
  dex/src/test/scala/com/wavesplatform/dex/market/MatcherSpec.scala
  dex/src/test/scala/com/wavesplatform/dex/model/EventJsonSpecification.scala
  dex/src/test/scala/com/wavesplatform/dex/settings/MatcherSettingsSpecification.scala
  project/Dependencies.scala
  project/ReleasePlugin.scala
  project/plugins.sbt
  waves-integration-it/src/test/scala/com/wavesplatform/dex/grpc/integration/ItTestSuiteBase.scala
  waves-integration/build.sbt
  waves-integration/src/main/package/sample.conf
  waves-integration/src/main/resources/application.conf
Labels: documentation, enhancement

#109 DEX-491 Tick-size can have at max 8 decimals
  dex/src/main/scala/com/wavesplatform/dex/caches/MatchingRulesCache.scala
Labels: enhancement

#102 DEX-460 gRPC errors handling
  dex-it-tools/src/main/scala/com/wavesplatform/dex/it/docker/DockerContainerLauncher.scala
  dex-it-tools/src/main/scala/com/wavesplatform/dex/it/docker/WavesIntegrationItDocker.scala
  dex-it/src/test/scala/com/wavesplatform/it/MatcherSuiteBase.scala
  dex-it/src/test/scala/com/wavesplatform/it/api/DexApiOps.scala
  dex-it/src/test/scala/com/wavesplatform/it/async/CorrectStatusAfterPlaceTestSuite.scala
  dex-it/src/test/scala/com/wavesplatform/it/sync/DEXClientFaultToleranceTestSuite.scala
  dex-it/src/test/scala/com/wavesplatform/it/sync/MultipleMatchersTestSuite.scala
  dex-it/src/test/scala/com/wavesplatform/it/sync/smartcontracts/ExtraFeeTestSuite.scala
  dex/src/main/scala/com/wavesplatform/dex/AddressActor.scala
  dex/src/main/scala/com/wavesplatform/dex/AssetPairBuilder.scala
  dex/src/main/scala/com/wavesplatform/dex/Matcher.scala
  dex/src/main/scala/com/wavesplatform/dex/MatcherKeys.scala
  dex/src/main/scala/com/wavesplatform/dex/api/MatcherApiRoute.scala
  dex/src/main/scala/com/wavesplatform/dex/api/MatcherResponse.scala
  dex/src/main/scala/com/wavesplatform/dex/api/OrderBookSnapshotHttpCache.scala
  dex/src/main/scala/com/wavesplatform/dex/db/AssetsDB.scala
  dex/src/main/scala/com/wavesplatform/dex/effect/package.scala
  dex/src/main/scala/com/wavesplatform/dex/error/MatcherError.scala
  dex/src/main/scala/com/wavesplatform/dex/market/ExchangeTransactionBroadcastActor.scala
  dex/src/main/scala/com/wavesplatform/dex/market/MatcherActor.scala
  dex/src/main/scala/com/wavesplatform/dex/market/OrderBookActor.scala
  dex/src/main/scala/com/wavesplatform/dex/model/ExchangeTransactionCreator.scala
  dex/src/main/scala/com/wavesplatform/dex/model/OrderValidator.scala
  dex/src/main/scala/com/wavesplatform/dex/settings/DeviationsSettings.scala
  dex/src/main/scala/com/wavesplatform/dex/settings/MatchingRule.scala
  dex/src/main/scala/com/wavesplatform/dex/settings/OrderFeeSettings.scala
  dex/src/main/scala/com/wavesplatform/dex/settings/OrderHistorySettings.scala
  dex/src/main/scala/com/wavesplatform/dex/settings/OrderRestrictionsSettings.scala
  dex/src/main/scala/com/wavesplatform/dex/settings/PostgresConnection.scala
  dex/src/main/scala/future/com/wavesplatform/settings/utils/ConfigSettingsValidator.scala
  dex/src/test/scala/com/wavesplatform/dex/AssetPairBuilderSpec.scala
  dex/src/test/scala/com/wavesplatform/dex/MatcherTestData.scala
  dex/src/test/scala/com/wavesplatform/dex/api/MatcherApiRouteSpec.scala
  dex/src/test/scala/com/wavesplatform/dex/api/OrderBookSnapshotHttpCacheSpec.scala
  dex/src/test/scala/com/wavesplatform/dex/market/MatcherActorSpecification.scala
  dex/src/test/scala/com/wavesplatform/dex/market/OrderBookActorSpecification.scala
  dex/src/test/scala/com/wavesplatform/dex/model/ExchangeTransactionCreatorSpecification.scala
  dex/src/test/scala/com/wavesplatform/dex/model/OrderValidatorSpecification.scala
  dex/src/test/scala/com/wavesplatform/dex/settings/BaseSettingsSpecification.scala
  waves-integration-it/src/test/resources/nodes/waves-1.conf
  waves-integration-it/src/test/scala/com/wavesplatform/dex/grpc/integration/ItTestSuiteBase.scala
  waves-integration-it/src/test/scala/com/wavesplatform/dex/grpc/integration/sync/WavesBlockchainAsyncClientTestSuite.scala
  waves-integration-it/src/test/scala/com/wavesplatform/dex/grpc/integration/sync/WavesBlockchainSyncClientTestSuite.scala
  waves-integration/src/main/scala/com/wavesplatform/dex/grpc/integration/clients/async/WavesBlockchainAsyncClient.scala
  waves-integration/src/main/scala/com/wavesplatform/dex/grpc/integration/clients/async/WavesBlockchainGrpcAsyncClient.scala
  waves-integration/src/main/scala/com/wavesplatform/dex/grpc/integration/exceptions/UnexpectedConnectionException.scala
  waves-integration/src/main/scala/com/wavesplatform/dex/grpc/integration/exceptions/WavesNodeConnectionLostException.scala
  waves-integration/src/main/scala/com/wavesplatform/dex/grpc/integration/smart/MatcherScriptRunner.scala
  waves-integration/src/test/scala/com/wavesplatform/dex/grpc/integration/caches/BlockchainCacheSpecification.scala
Labels: enhancement

#119 DEX-492 withAuth refactoring
  dex/src/main/resources/application.conf
  dex/src/main/scala/com/wavesplatform/dex/Matcher.scala
  dex/src/main/scala/com/wavesplatform/dex/api/MatcherApiRoute.scala
  dex/src/main/scala/com/wavesplatform/dex/api/MatcherApiRouteV1.scala
  dex/src/main/scala/com/wavesplatform/dex/api/http/AuthRoute.scala
  dex/src/main/scala/com/wavesplatform/dex/error/MatcherError.scala
  dex/src/test/scala/com/wavesplatform/dex/api/MatcherApiRouteSpec.scala
Labels: enhancement

#116 DEX-515 Correct matcher response for the invalid order json
  dex-it/src/test/scala/com/wavesplatform/it/api/AsyncMatcherHttpApi.scala
  dex-it/src/test/scala/com/wavesplatform/it/api/SyncMatcherHttpApi.scala
  dex-it/src/test/scala/com/wavesplatform/it/sync/OrderRestrictionsTestSuite.scala
  dex/src/main/scala/com/wavesplatform/dex/api/MatcherApiRoute.scala
  dex/src/main/scala/com/wavesplatform/dex/api/MatcherResponse.scala
  dex/src/main/scala/com/wavesplatform/dex/error/MatcherError.scala
  dex/src/test/scala/com/wavesplatform/dex/api/MatcherApiRouteSpec.scala
Labels: bug-fix, version-1.1.x

#120 DEX-462 Better error for WAVES as Base58 in matcherFeeAssetId field
  dex/src/main/scala/com/wavesplatform/dex/error/MatcherError.scala
  dex/src/main/scala/com/wavesplatform/dex/model/MatcherModel.scala
  dex/src/test/scala/com/wavesplatform/dex/model/OrderValidatorSpecification.scala
Labels: bug-fix, version-1.1.x
