Repository wavesplatform/matcher, pull requests merged in 2019-12, with the labels that each got.

#121 DEX-520 ErrorInterpolator type classes refactoring
  dex/src/main/scala/com/wavesplatform/dex/error/ContextShow.scala
  dex/src/main/scala/com/wavesplatform/dex/error/ContextWrites.scala
  dex/src/main/scala/com/wavesplatform/dex/error/Implicits.scala
  dex/src/main/scala/com/wavesplatform/dex/meta/Sample.scala
Labels: enhancement, question

#122 DEX-521 Wrong cancel
  dex-it/src/test/scala/com/wavesplatform/it/sync/CancelOrderTestSuite.scala
  dex/src/main/scala/com/wavesplatform/dex/AddressActor.scala
  dex/src/main/scala/com/wavesplatform/dex/Matcher.scala
  dex/src/main/scala/com/wavesplatform/dex/market/CreateExchangeTransactionActor.scala
  dex/src/main/scala/com/wavesplatform/dex/market/OrderBookActor.scala
  dex/src/test/scala/com/wavesplatform/dex/market/MatcherActorSpecification.scala
  dex/src/test/scala/com/wavesplatform/dex/market/OrderBookActorSpecification.scala
Labels: bug-fix

#118 DEX-496 diffx in tests
  dex-it-tools/src/main/scala/com/wavesplatform/dex/it/json/package.scala
  dex-it/src/test/scala/com/wavesplatform/it/MatcherSuiteBase.scala
  dex-it/src/test/scala/com/wavesplatform/it/api/DexApi.scala
  dex-it/src/test/scala/com/wavesplatform/it/api/DexApiOps.scala
  dex-it/src/test/scala/com/wavesplatform/it/api/MatcherState.scala
  dex-it/src/test/scala/com/wavesplatform/it/sync/MultipleMatchersTestSuite.scala
  dex-it/src/test/scala/com/wavesplatform/it/sync/OrderBookSnapshotsTestSuite.scala
  dex-it/src/test/scala/com/wavesplatform/it/sync/api/GetOrderBookTestSuite.scala
  dex-it/src/test/scala/com/wavesplatform/it/test/ApiExtensions.scala
  dex-it/src/test/scala/com/wavesplatform/it/test/ItMatchers.scala
  dex/src/main/scala/com/wavesplatform/dex/db/AssetPairsDB.scala
  dex/src/main/scala/com/wavesplatform/dex/fp/MapImplicits.scala
  dex/src/main/scala/com/wavesplatform/dex/model/Implicits.scala
  dex/src/main/scala/com/wavesplatform/dex/queue/KafkaMatcherQueue.scala
  dex/src/main/scala/com/wavesplatform/dex/settings/ConfigExtraOps.scala
  dex/src/main/scala/com/wavesplatform/dex/settings/DeviationsSettings.scala
  dex/src/main/scala/com/wavesplatform/dex/settings/Implicits.scala
  dex/src/main/scala/com/wavesplatform/dex/settings/MatcherSettings.scala
  dex/src/main/scala/com/wavesplatform/dex/settings/MatchingRule.scala
  dex/src/main/scala/com/wavesplatform/dex/settings/OrderFeeSettings.scala
  dex/src/main/scala/com/wavesplatform/dex/settings/OrderHistorySettings.scala
  dex/src/main/scala/com/wavesplatform/dex/settings/OrderRestrictionsSettings.scala
  dex/src/main/scala/com/wavesplatform/dex/settings/PostgresConnection.scala
  dex/src/main/scala/com/wavesplatform/dex/settings/package.scala
  dex/src/main/scala/com/wavesplatform/dex/settings/utils/ConfigOps.scala
  dex/src/main/scala/com/wavesplatform/dex/settings/utils/ConfigSettingsValidator.scala
  dex/src/main/scala/future/com/wavesplatform/transaction/assets/exchange/Implicits.scala
  dex/src/test/scala/com/wavesplatform/dex/MatcherTestData.scala
  dex/src/test/scala/com/wavesplatform/dex/settings/MatcherSettingsSpecification.scala
  dex/src/test/scala/com/wavesplatform/dex/settings/MatchingRulesSpecification.scala
  dex/src/test/scala/com/wavesplatform/dex/test/matchers/DiffMatcherWithImplicits.scala
  project/Dependencies.scala
Labels: enhancement

#127 DEX-528 Dependencies refactoring
  project/Dependencies.scala
  project/Network.scala
Labels: enhancement

#128 DEX-530 Exceptions during big block application
  dex-it/src/test/scala/com/wavesplatform/it/api/SyncMatcherHttpApi.scala
  dex-it/src/test/scala/com/wavesplatform/it/sync/CancelOrderTestSuite.scala
  dex-it/src/test/scala/com/wavesplatform/it/sync/MarketOrderTestSuite.scala
  dex-it/src/test/scala/com/wavesplatform/it/sync/PostgresHistoryDatabaseTestSuite.scala
  dex/src/main/resources/application.conf
  dex/src/main/scala/com/wavesplatform/dex/market/ExchangeTransactionBroadcastActor.scala
  dex/src/test/scala/com/wavesplatform/dex/market/ExchangeTransactionBroadcastActorSpecification.scala
Labels: bug-fix

#126 DEX-525 Improve DEX extension for NODE
  build.sbt
  dex-test-common/build.sbt
  dex-test-common/src/main/scala/com/wavesplatform/dex/test/matchers/DiffMatcherWithImplicits.scala
  dex/src/main/scala/com/wavesplatform/dex/AddressDirectory.scala
  dex/src/main/scala/com/wavesplatform/dex/Application.scala
  dex/src/main/scala/com/wavesplatform/dex/Matcher.scala
  dex/src/main/scala/com/wavesplatform/dex/meta/Sample.scala
  dex/src/main/scala/com/wavesplatform/dex/model/OrderValidator.scala
  dex/src/test/scala/com/wavesplatform/dex/MatcherTestData.scala
  dex/src/test/scala/com/wavesplatform/dex/market/OrderBookActorSpecification.scala
  dex/src/test/scala/com/wavesplatform/dex/matching/ReservedBalanceSpecification.scala
  dex/src/test/scala/com/wavesplatform/dex/model/OrderValidatorSpecification.scala
  project/Dependencies.scala
  project/build.properties
  waves-integration-it/src/test/resources/logback-test.xml
  waves-integration-it/src/test/scala/com/wavesplatform/dex/grpc/integration/ItTestSuiteBase.scala
  waves-integration-it/src/test/scala/com/wavesplatform/dex/grpc/integration/clients/WavesBlockchainAsyncClientTestSuite.scala
  waves-integration-it/src/test/scala/com/wavesplatform/dex/grpc/integration/sync/WavesBlockchainAsyncClientTestSuite.scala
  waves-integration-it/src/test/scala/com/wavesplatform/dex/grpc/integration/sync/WavesBlockchainSyncClientTestSuite.scala
  waves-integration/build.sbt
  waves-integration/src/main/protobuf/waves_balances_api.proto
  waves-integration/src/main/protobuf/waves_blockchain_api.proto
  waves-integration/src/main/scala/com/wavesplatform/dex/grpc/integration/DEXClient.scala
  waves-integration/src/main/scala/com/wavesplatform/dex/grpc/integration/DEXExtension.scala
  waves-integration/src/main/scala/com/wavesplatform/dex/grpc/integration/clients/RunScriptResult.scala
  waves-integration/src/main/scala/com/wavesplatform/dex/grpc/integration/clients/WavesBlockchainCachingClient.scala
  waves-integration/src/main/scala/com/wavesplatform/dex/grpc/integration/clients/WavesBlockchainClient.scala
  waves-integration/src/main/scala/com/wavesplatform/dex/grpc/integration/clients/WavesBlockchainGrpcAsyncClient.scala
  waves-integration/src/main/scala/com/wavesplatform/dex/grpc/integration/clients/async/WavesBlockchainCachingClient.scala
  waves-integration/src/main/scala/com/wavesplatform/dex/grpc/integration/clients/sync/WavesBlockchainClient.scala
  waves-integration/src/main/scala/com/wavesplatform/dex/grpc/integration/clients/sync/WavesBlockchainGrpcSyncClient.scala
  waves-integration/src/main/scala/com/wavesplatform/dex/grpc/integration/protobuf/GRPCErrors.scala
  waves-integration/src/main/scala/com/wavesplatform/dex/grpc/integration/protobuf/package.scala
  waves-integration/src/main/scala/com/wavesplatform/dex/grpc/integration/services/WavesBalancesApiGrpcServer.scala
  waves-integration/src/main/scala/com/wavesplatform/dex/grpc/integration/services/WavesBlockchainApiGrpcServer.scala
Labels: enhancement

#129 DEX-529 DEB should be installed without errors
  README.md
  dex-it/build.sbt
  dex-it/src/test/resources/logback-container.xml
  dex-it/src/test/resources/logback-test.xml
  dex-it/src/test/scala/com/wavesplatform/it/docker/DexItDocker.scala
  dex/build.sbt
  dex/src/main/container/start.sh
  dex/src/main/resources/application.conf
  dex/src/package/debian/postinst
  dex/src/package/debian/postrm
  dex/src/package/debian/preinst
  dex/src/package/debian/prerm
  dex/src/package/doc/README.md
  dex/src/package/doc/devnet.conf
  dex/src/package/doc/logback.xml
  dex/src/package/doc/mainnet.conf
  dex/src/package/doc/stagenet.conf
  dex/src/package/doc/testnet.conf
  dex/src/package/systemd.service
  dex/src/package/upstart.conf
  project/Dependencies.scala
  waves-integration/build.sbt
Labels: bug-fix

#130 DEX-537 Distinguishing limit and market orders in order history
  dex-it/src/test/scala/com/wavesplatform/it/api/model.scala
  dex-it/src/test/scala/com/wavesplatform/it/sync/MarketOrderTestSuite.scala
  dex-it/src/test/scala/com/wavesplatform/it/sync/MatcherTestSuite.scala
  dex/src/main/scala/com/wavesplatform/dex/AddressActor.scala
  dex/src/main/scala/com/wavesplatform/dex/api/MatcherApiRoute.scala
  dex/src/main/scala/com/wavesplatform/dex/model/AcceptedOrderType.scala
  dex/src/main/scala/com/wavesplatform/dex/model/OrderInfo.scala
  dex/src/main/scala/com/wavesplatform/dex/util/Codecs.scala
Labels: enhancement

#140 DEX-555 Waves extension force shutdown
  waves-integration/src/main/scala/com/wavesplatform/dex/grpc/integration/DEXExtension.scala
  waves-integration/src/main/scala/com/wavesplatform/dex/grpc/integration/clients/WavesBlockchainGrpcAsyncClient.scala
Labels: bug-fix
