Repository wavesplatform/matcher, pull requests merged in 2019-07, with the labels that each got.

#14 DEX-352 The matcher fee in REST API
  build.sbt
  dex/src/main/scala/com/wavesplatform/dex/AddressActor.scala
  dex/src/main/scala/com/wavesplatform/dex/MatcherTool.scala
  dex/src/main/scala/com/wavesplatform/dex/api/MatcherApiRoute.scala
  dex/src/main/scala/com/wavesplatform/dex/model/MatcherModel.scala
  dex/src/main/scala/com/wavesplatform/dex/model/OrderInfo.scala
  dex/src/main/scala/com/wavesplatform/dex/util/Codecs.scala
  dex/src/test/scala/com/wavesplatform/dex/model/OrderDBSpec.scala
  dex/src/test/scala/com/wavesplatform/dex/model/OrderHistoryBalanceSpecification.scala
  dex/src/test/scala/com/wavesplatform/dex/model/OrderInfoSpec.scala
  project/plugins.sbt
Labels: enhancement

#17 DEX-360 MatcherContext should have "this"
  dex/src/main/scala/com/wavesplatform/dex/smart/MatcherContext.scala
Labels: bug

#19 DEX-362 OrderInfo migration errors
  dex/src/main/scala/com/wavesplatform/dex/MatcherTool.scala
  dex/src/main/scala/com/wavesplatform/dex/model/OrderInfo.scala
Labels: bug

#16 DEX-350 Releasing process
  README.md
  build.sbt
  project/Hashes.scala
  project/Network.scala
  project/ReleasePlugin.scala
Labels: documentation, enhancement

#18 DEX-361 dApp execution error during order placement
  dex-it/src/test/scala/com/wavesplatform/it/sync/smartcontracts/OrdersFromScriptedAccTestSuite.scala
  dex-it/src/test/scala/com/wavesplatform/it/sync/smartcontracts/ProofAndAssetPairTestSuite.scala
  dex/src/main/scala/com/wavesplatform/dex/error/package.scala
  dex/src/main/scala/com/wavesplatform/dex/model/OrderValidator.scala
  dex/src/main/scala/com/wavesplatform/dex/smart/MatcherContext.scala
  dex/src/main/scala/com/wavesplatform/dex/smart/MatcherScriptRunner.scala
  dex/src/test/scala/com/wavesplatform/dex/error/ProduceError.scala
  dex/src/test/scala/com/wavesplatform/dex/model/OrderValidatorSpecification.scala
  dex/src/test/scala/com/wavesplatform/dex/smart/MatcherScriptRunnerTest.scala
Labels: bug, enhancement

#13 DEX-88 Market orders introduced
  dex-it/src/test/scala/com/wavesplatform/it/api/AsyncMatcherHttpApi.scala
  dex-it/src/test/scala/com/wavesplatform/it/api/SyncMatcherHttpApi.scala
  dex-it/src/test/scala/com/wavesplatform/it/sync/MarketOrderTestSuite.scala
  dex-it/src/test/scala/com/wavesplatform/it/sync/OrderHistoryTestSuite.scala
  dex-it/src/test/scala/com/wavesplatform/it/sync/TradeBalanceAndRoundingTestSuite.scala
  dex/src/main/resources/application.conf
  dex/src/main/resources/order-history/order-history-ddl.sql
  dex/src/main/scala/com/wavesplatform/dex/AddressActor.scala
  dex/src/main/scala/com/wavesplatform/dex/AddressDirectory.scala
  dex/src/main/scala/com/wavesplatform/dex/Matcher.scala
  dex/src/main/scala/com/wavesplatform/dex/api/MatcherApiRoute.scala
  dex/src/main/scala/com/wavesplatform/dex/error/MatcherError.scala
  dex/src/main/scala/com/wavesplatform/dex/history/DBRecords.scala
  dex/src/main/scala/com/wavesplatform/dex/history/HistoryRouter.scala
  dex/src/main/scala/com/wavesplatform/dex/market/OrderBookActor.scala
  dex/src/main/scala/com/wavesplatform/dex/model/ExchangeTransactionCreator.scala
  dex/src/main/scala/com/wavesplatform/dex/model/MatcherModel.scala
  dex/src/main/scala/com/wavesplatform/dex/model/OrderBook.scala
  dex/src/main/scala/com/wavesplatform/dex/model/OrderValidator.scala
  dex/src/main/scala/com/wavesplatform/dex/queue/QueueEvent.scala
  dex/src/main/scala/com/wavesplatform/dex/queue/QueueEventWithMeta.scala
  dex/src/test/scala/com/wavesplatform/dex/AddressActorSpecification.scala
  dex/src/test/scala/com/wavesplatform/dex/MatcherTestData.scala
  dex/src/test/scala/com/wavesplatform/dex/history/HistoryRouterSpecification.scala
  dex/src/test/scala/com/wavesplatform/dex/market/MatcherActorSpecification.scala
  dex/src/test/scala/com/wavesplatform/dex/market/OrderBookActorSpecification.scala
  dex/src/test/scala/com/wavesplatform/dex/matching/ReservedBalanceSpecification.scala
  dex/src/test/scala/com/wavesplatform/dex/model/OrderBookSpec.scala
  dex/src/test/scala/com/wavesplatform/dex/model/OrderHistoryBalanceSpecification.scala
  dex/src/test/scala/com/wavesplatform/dex/model/OrderHistoryStub.scala
  dex/src/test/scala/com/wavesplatform/dex/model/OrderValidatorSpecification.scala
Labels: enhancement

#15 DEX-339 Order History improvements
  dex-it/src/test/scala/com/wavesplatform/it/sync/OrderHistoryTestSuite.scala
  dex/src/main/resources/order-history/order-history-ddl.sql
  dex/src/main/scala/com/wavesplatform/dex/Matcher.scala
  dex/src/main/scala/com/wavesplatform/dex/api/MatcherApiRoute.scala
  dex/src/main/scala/com/wavesplatform/dex/api/MatcherApiRouteV1.scala
  dex/src/main/scala/com/wavesplatform/dex/cache/AssetDecimalsCache.scala
  dex/src/main/scala/com/wavesplatform/dex/cache/RateCache.scala
  dex/src/main/scala/com/wavesplatform/dex/history/DBRecords.scala
  dex/src/main/scala/com/wavesplatform/dex/history/HistoryRouter.scala
  dex/src/main/scala/com/wavesplatform/dex/model/MatcherModel.scala
  dex/src/main/scala/com/wavesplatform/dex/model/OrderValidator.scala
  dex/src/test/scala/com/wavesplatform/dex/MatcherTestData.scala
  dex/src/test/scala/com/wavesplatform/dex/api/MatcherApiRouteSpec.scala
  dex/src/test/scala/com/wavesplatform/dex/model/OrderValidatorSpecification.scala
Labels: enhancement
