Repository wavesplatform/matcher, pull requests merged in 2019-09, with the labels that each got.

#43 DEX-399 Balance cache
  dex-it/src/test/resources/nodes/dex-1.conf
  dex-it/src/test/scala/com/wavesplatform/it/NewMatcherSuiteBase.scala
  dex-it/src/test/scala/com/wavesplatform/it/api/DexApi.scala
  dex-it/src/test/scala/com/wavesplatform/it/api/LoggingSttpBackend.scala
  dex-it/src/test/scala/com/wavesplatform/it/api/NodeApi.scala
  dex-it/src/test/scala/com/wavesplatform/it/config/DexTestConfig.scala
  dex-it/src/test/scala/com/wavesplatform/it/fp/package.scala
  dex-it/src/test/scala/com/wavesplatform/it/sync/BlacklistedTradingTestSuite.scala
  dex-it/src/test/scala/com/wavesplatform/it/sync/BroadcastUntilConfirmedTestSuite.scala
  dex-it/src/test/scala/com/wavesplatform/it/sync/CancelOrderTestSuite.scala
  dex-it/src/test/scala/com/wavesplatform/it/sync/DisableProducerTestSuite.scala
  dex-it/src/test/scala/com/wavesplatform/it/sync/MarketOrderTestSuite.scala
  dex-it/src/test/scala/com/wavesplatform/it/sync/MatcherMassOrdersTestSuite.scala
  dex-it/src/test/scala/com/wavesplatform/it/sync/MatcherRecoveryTestSuite.scala
  dex-it/src/test/scala/com/wavesplatform/it/sync/MatcherRestartTestSuite.scala
  dex-it/src/test/scala/com/wavesplatform/it/sync/MatcherRulesTestSuite.scala
  dex-it/src/test/scala/com/wavesplatform/it/sync/MatcherTestSuite.scala
  dex-it/src/test/scala/com/wavesplatform/it/sync/TradersTestSuite.scala
  dex-it/src/test/scala/com/wavesplatform/it/sync/TradingMarketsTestSuite.scala
  dex-it/src/test/scala/com/wavesplatform/it/test/FailWith.scala
  dex/src/main/scala/com/wavesplatform/dex/AddressActor.scala
  dex/src/main/scala/com/wavesplatform/dex/AddressDirectory.scala
  dex/src/main/scala/com/wavesplatform/dex/Application.scala
  dex/src/main/scala/com/wavesplatform/dex/Matcher.scala
  dex/src/main/scala/com/wavesplatform/dex/cache/AssetDecimalsCache.scala
  dex/src/main/scala/com/wavesplatform/dex/cache/BalancesCache.scala
  dex/src/main/scala/com/wavesplatform/dex/model/OrderValidator.scala
  dex/src/test/scala/com/wavesplatform/dex/AssetPairDecimals.scala
  dex/src/test/scala/com/wavesplatform/dex/matching/ReservedBalanceSpecification.scala
  dex/src/test/scala/com/wavesplatform/dex/model/OrderValidatorSpecification.scala
  waves-integration-it/src/test/scala/com/wavesplatform/dex/grpc/integration/ItTestSuiteBase.scala
  waves-integration-it/src/test/scala/com/wavesplatform/dex/grpc/integration/config/Assets.scala
  waves-integration-it/src/test/scala/com/wavesplatform/dex/grpc/integration/sync/WavesGrpcAsyncClientTestSuite.scala
  waves-integration-it/src/test/scala/com/wavesplatform/dex/grpc/integration/sync/WavesGrpcSyncClientTestSuite.scala
  waves-integration/src/main/protobuf/waves_balances_api.proto
  waves-integration/src/main/protobuf/waves_blockchain_api.proto
  waves-integration/src/main/scala/com/wavesplatform/dex/grpc/integration/DEXClient.scala
  waves-integration/src/main/scala/com/wavesplatform/dex/grpc/integration/DEXExtension.scala
  waves-integration/src/main/scala/com/wavesplatform/dex/grpc/integration/client/WavesBlockchainSyncGrpcContext.scala
  waves-integration/src/main/scala/com/wavesplatform/dex/grpc/integration/clients/async/WavesBalancesClient.scala
  waves-integration/src/main/scala/com/wavesplatform/dex/grpc/integration/clients/async/WavesBalancesGrpcAsyncClient.scala
  waves-integration/src/main/scala/com/wavesplatform/dex/grpc/integration/clients/sync/WavesBlockchainClient.scala
  waves-integration/src/main/scala/com/wavesplatform/dex/grpc/integration/clients/sync/WavesBlockchainGrpcSyncClient.scala
  waves-integration/src/main/scala/com/wavesplatform/dex/grpc/integration/error/package.scala
  waves-integration/src/main/scala/com/wavesplatform/dex/grpc/integration/protobuf/Implicits.scala
  waves-integration/src/main/scala/com/wavesplatform/dex/grpc/integration/protobuf/ToPbConversions.scala
  waves-integration/src/main/scala/com/wavesplatform/dex/grpc/integration/protobuf/ToVanillaConversions.scala
  waves-integration/src/main/scala/com/wavesplatform/dex/grpc/integration/services/WavesBalancesApiGrpcServer.scala
  waves-integration/src/main/scala/com/wavesplatform/dex/grpc/integration/services/WavesBlockchainApiGrpcServer.scala
  waves-integration/src/main/scala/com/wavesplatform/dex/grpc/integration/smart/MatcherContext.scala
Labels: enhancement

#45 DEX-389 Stagenet support
  dex/dex-stagenet.conf
  project/Network.scala
Labels: enhancement

#40 DEX-366 Dynamic order fee mode fix
  build.sbt
  dex-generator/src/main/scala/com/wavesplatform/dexgen/DexGenApp.scala
  dex-generator/src/main/scala/com/wavesplatform/dexgen/Worker.scala
  dex-it/src/test/scala/com/wavesplatform/it/MatcherNode.scala
  dex-it/src/test/scala/com/wavesplatform/it/api/AsyncMatcherHttpApi.scala
  dex-it/src/test/scala/com/wavesplatform/it/sync/BlacklistedTradingTestSuite.scala
  dex-it/src/test/scala/com/wavesplatform/it/sync/DisableProducerTestSuite.scala
  dex-it/src/test/scala/com/wavesplatform/it/sync/MatcherMassOrdersTestSuite.scala
  dex-it/src/test/scala/com/wavesplatform/it/sync/MatcherRestartTestSuite.scala
  dex-it/src/test/scala/com/wavesplatform/it/sync/MatcherTestSuite.scala
  dex-it/src/test/scala/com/wavesplatform/it/sync/MultipleMatchersTestSuite.scala
  dex-it/src/test/scala/com/wavesplatform/it/sync/RoundingIssuesTestSuite.scala
  dex-it/src/test/scala/com/wavesplatform/it/sync/SeveralPartialOrdersTestSuite.scala
  dex-it/src/test/scala/com/wavesplatform/it/sync/TradeBalanceAndRoundingTestSuite.scala
  dex-it/src/test/scala/com/wavesplatform/it/sync/TradersTestSuite.scala
  dex-it/src/test/scala/com/wavesplatform/it/sync/smartcontracts/ExtraFeeTestSuite.scala
  dex-it/src/test/scala/com/wavesplatform/it/sync/smartcontracts/OrdersFromScriptedAccTestSuite.scala
  dex-it/src/test/scala/com/wavesplatform/it/sync/smartcontracts/OrdersFromScriptedAssetTestSuite.scala
  dex-it/src/test/scala/com/wavesplatform/it/sync/smartcontracts/ProofAndAssetPairTestSuite.scala
  dex/src/main/scala/com/wavesplatform/dex/Matcher.scala
  dex/src/main/scala/com/wavesplatform/dex/MatcherSnapshotStore.scala
  dex/src/main/scala/com/wavesplatform/dex/MatcherTool.scala
  dex/src/main/scala/com/wavesplatform/dex/api/MatcherApiRoute.scala
  dex/src/main/scala/com/wavesplatform/dex/api/MatcherApiRouteV1.scala
  dex/src/main/scala/com/wavesplatform/dex/history/HistoryRouter.scala
  dex/src/main/scala/com/wavesplatform/dex/model/ExchangeTransactionCreator.scala
  dex/src/main/scala/com/wavesplatform/dex/model/MatcherModel.scala
  dex/src/main/scala/com/wavesplatform/dex/model/OrderValidator.scala
  dex/src/main/scala/com/wavesplatform/dex/smart/MatcherContext.scala
  dex/src/main/scala/com/wavesplatform/dex/smart/MatcherScriptRunner.scala
  dex/src/test/scala/com/wavesplatform/dex/MatcherTestData.scala
  dex/src/test/scala/com/wavesplatform/dex/api/MatcherApiRouteSpec.scala
  dex/src/test/scala/com/wavesplatform/dex/model/OrderValidatorSpecification.scala
  dex/src/test/scala/com/wavesplatform/dex/smart/MatcherScriptRunnerTest.scala
  dex/src/test/scala/com/wavesplatform/state/diffs/package.scala
  project/Dependencies.scala
  project/plugins.sbt
Labels: bug-fix, version-1.0.x

#41 DEX-381 Forbid 0 price level
  build.sbt
  dex-it/src/test/resources/template.conf
  dex/src/main/scala/com/wavesplatform/dex/Matcher.scala
  dex/src/main/scala/com/wavesplatform/dex/error/MatcherError.scala
  dex/src/main/scala/com/wavesplatform/dex/model/OrderBook.scala
  dex/src/main/scala/com/wavesplatform/dex/model/OrderValidator.scala
  dex/src/main/scala/com/wavesplatform/dex/smart/MatcherContext.scala
  dex/src/test/scala/com/wavesplatform/dex/model/OrderValidatorSpecification.scala
  dex/src/test/scala/com/wavesplatform/state/diffs/package.scala
Labels: bug-fix, version-1.0.x

#44 DEX-395 Java 11 support
  README.md
  build.sbt
  dex/dex-stagenet.conf
  dex/src/main/scala/com/wavesplatform/dex/api/MatcherApiRoute.scala
  dex/src/main/scala/com/wavesplatform/dex/api/http/CompositeHttpService.scala
  dex/src/main/scala/com/wavesplatform/dex/doc/DocGeneratorApp.scala
  dex/src/main/scala/com/wavesplatform/dex/market/MatcherActor.scala
  dex/src/main/scala/com/wavesplatform/dex/model/ExchangeTransactionCreator.scala
  dex/src/main/scala/com/wavesplatform/dex/model/OrderValidator.scala
  dex/src/main/scala/com/wavesplatform/dex/smart/MatcherContext.scala
  dex/src/test/scala/com/wavesplatform/state/diffs/package.scala
  project/CommonSettings.scala
  project/Dependencies.scala
  project/ItTestPlugin.scala
  project/ModernJavaSettings.scala
  project/Network.scala
  project/ReleasePlugin.scala
  project/plugins.sbt
Labels: bug-fix, documentation, enhancement, version-1.0.x

#52 DEX-402 History Database fee denormalization fix
  dex-it/src/test/scala/com/wavesplatform/it/api/AsyncMatcherHttpApi.scala
  dex-it/src/test/scala/com/wavesplatform/it/api/SyncMatcherHttpApi.scala
  dex-it/src/test/scala/com/wavesplatform/it/sync/OrderHistoryTestSuite.scala
  dex-it/src/test/scala/com/wavesplatform/it/sync/config/MatcherPriceAssetConfig.scala
  dex/src/main/resources/order-history/order-history-ddl.sql
  dex/src/main/scala/com/wavesplatform/dex/history/DBRecords.scala
  dex/src/main/scala/com/wavesplatform/dex/history/HistoryRouter.scala
  dex/src/main/scala/com/wavesplatform/dex/model/MatcherModel.scala
  dex/src/test/scala/com/wavesplatform/dex/AssetPairDecimals.scala
  dex/src/test/scala/com/wavesplatform/dex/history/HistoryRouterSpecification.scala
Labels: bug-fix, version-1.0.x

#54 DEX-406 Stagenet Node tag
  build.sbt
Labels: version-1.0.x

#57 DEX-410 Node's version updated to 1.1.2
  build.sbt
  dex/src/main/scala/com/wavesplatform/dex/model/ExchangeTransactionCreator.scala
Labels: version-1.0.x

#56 DEX-404 Price level 0 is forbidden for buy orders
  dex-it/src/test/scala/com/wavesplatform/it/sync/MatchingRulesTestSuite.scala
  dex/src/main/scala/com/wavesplatform/dex/Matcher.scala
  dex/src/main/scala/com/wavesplatform/dex/market/OrderBookActor.scala
  dex/src/main/scala/com/wavesplatform/dex/settings/MatcherSettings.scala
  dex/src/main/scala/com/wavesplatform/dex/settings/MatchingRule.scala
  dex/src/test/scala/com/wavesplatform/dex/market/MatcherActorSpecification.scala
  dex/src/test/scala/com/wavesplatform/dex/market/OrderBookActorSpecification.scala
  dex/src/test/scala/com/wavesplatform/dex/model/DenormalizedMatchingRulesSpecification.scala
  dex/src/test/scala/com/wavesplatform/dex/settings/MatcherSettingsSpecification.scala
Labels: version-1.0.x

#60 DEX-412 Old orders matching fix
  dex/src/main/scala/com/wavesplatform/dex/model/OrderBook.scala
  dex/src/test/scala/com/wavesplatform/dex/MatcherTestData.scala
  dex/src/test/scala/com/wavesplatform/dex/model/OrderBookSpec.scala
  dex/src/test/scala/com/wavesplatform/dex/model/OrderValidatorSpecification.scala
Labels: bug-fix, version-1.0.x
