Repository wavesplatform/matcher, pull requests merged in 2020-03, with the labels that each got.

#171 DEX-596 Authenticated Web Socket stream
  dex-it-common/src/main/scala/com/wavesplatform/dex/it/api/websockets/HasWebSockets.scala
  dex-it-common/src/main/scala/com/wavesplatform/dex/it/api/websockets/WebSocketConnection.scala
  dex-it-common/src/main/scala/com/wavesplatform/dex/it/config/PredefinedAssets.scala
  dex-it/src/test/scala/com/wavesplatform/it/MatcherSuiteBase.scala
  dex-it/src/test/scala/com/wavesplatform/it/sync/MatcherTickerTestSuite.scala
  dex-it/src/test/scala/com/wavesplatform/it/sync/api/MatcherWebSocketsTestSuite.scala
  dex/src/main/resources/application.conf
  dex/src/main/scala/com/wavesplatform/dex/AddressActor.scala
  dex/src/main/scala/com/wavesplatform/dex/AddressDirectory.scala
  dex/src/main/scala/com/wavesplatform/dex/AddressWsMutableState.scala
  dex/src/main/scala/com/wavesplatform/dex/Matcher.scala
  dex/src/main/scala/com/wavesplatform/dex/SpendableBalancesActor.scala
  dex/src/main/scala/com/wavesplatform/dex/api/MatcherWebSocketRoute.scala
  dex/src/main/scala/com/wavesplatform/dex/api/websockets/WsAddressState.scala
  dex/src/main/scala/com/wavesplatform/dex/api/websockets/WsBalances.scala
  dex/src/main/scala/com/wavesplatform/dex/settings/MatcherSettings.scala
  dex/src/main/scala/com/wavesplatform/dex/settings/WebSocketSettings.scala
  dex/src/test/scala/com/wavesplatform/dex/ActorsWebSocketInteractionsSpecification.scala
  dex/src/test/scala/com/wavesplatform/dex/AddressActorSpecification.scala
  dex/src/test/scala/com/wavesplatform/dex/MatcherSpecBase.scala
  dex/src/test/scala/com/wavesplatform/dex/SpendableBalancesActorSpecification.scala
  dex/src/test/scala/com/wavesplatform/dex/api/websockets/WebSocketMessagesSerdeSpecification.scala
  dex/src/test/scala/com/wavesplatform/dex/grpc/integration/clients/WavesBlockchainCachingClientSpecification.scala
  dex/src/test/scala/com/wavesplatform/dex/matching/ReservedBalanceSpecification.scala
  dex/src/test/scala/com/wavesplatform/dex/model/OrderHistoryStub.scala
  dex/src/test/scala/com/wavesplatform/dex/model/OrderValidatorSpecification.scala
  dex/src/test/scala/com/wavesplatform/dex/settings/BaseSettingsSpecification.scala
  dex/src/test/scala/com/wavesplatform/dex/settings/MatcherSettingsSpecification.scala
  waves-ext/src/main/scala/com/wavesplatform/dex/grpc/integration/services/WavesBlockchainApiGrpcService.scala
  waves-grpc/src/main/protobuf/waves_blockchain_api.proto
  waves-integration-it/src/test/scala/com/wavesplatform/dex/grpc/integration/clients/WavesBlockchainAsyncClientTestSuite.scala
  waves-integration/src/main/scala/com/wavesplatform/dex/domain/asset/Asset.scala
  waves-integration/src/main/scala/com/wavesplatform/dex/grpc/integration/clients/WavesBlockchainCachingClient.scala
  waves-integration/src/main/scala/com/wavesplatform/dex/grpc/integration/clients/WavesBlockchainClient.scala
  waves-integration/src/main/scala/com/wavesplatform/dex/grpc/integration/clients/WavesBlockchainGrpcAsyncClient.scala
Labels: enhancement

#190 DEX-629 Orders changes WS support
  dex-it-common/src/main/scala/com/wavesplatform/dex/it/api/websockets/HasWebSockets.scala
  dex-it-common/src/main/scala/com/wavesplatform/dex/it/api/websockets/WebSocketAuthenticatedConnection.scala
  dex-it-common/src/main/scala/com/wavesplatform/dex/it/api/websockets/WebSocketConnection.scala
  dex-it/src/test/scala/com/wavesplatform/it/sync/api/MatcherWebSocketsTestSuite.scala
  dex/src/main/scala/com/wavesplatform/dex/AddressActor.scala
  dex/src/main/scala/com/wavesplatform/dex/AddressWsMutableState.scala
  dex/src/main/scala/com/wavesplatform/dex/MatcherKeys.scala
  dex/src/main/scala/com/wavesplatform/dex/api/websockets/WsAddressState.scala
  dex/src/main/scala/com/wavesplatform/dex/api/websockets/WsBalances.scala
  dex/src/main/scala/com/wavesplatform/dex/api/websockets/WsOrder.scala
  dex/src/main/scala/com/wavesplatform/dex/api/websockets/package.scala
  dex/src/main/scala/com/wavesplatform/dex/market/OrderBookSnapshotStoreActor.scala
  dex/src/main/scala/com/wavesplatform/dex/model/MatcherModel.scala
  dex/src/main/scala/com/wavesplatform/dex/model/OrderValidator.scala
  dex/src/test/scala/com/wavesplatform/dex/ActorsWebSocketInteractionsSpecification.scala
  dex/src/test/scala/com/wavesplatform/dex/api/websockets/WebSocketMessagesSerdeSpecification.scala
  dex/src/test/scala/com/wavesplatform/dex/market/ExchangeTransactionBroadcastActorSpecification.scala
  dex/src/test/scala/com/wavesplatform/dex/matching/ReservedBalanceSpecification.scala
  dex/src/test/scala/com/wavesplatform/dex/model/OrderBookTestSuite.scala
  dex/src/test/scala/com/wavesplatform/dex/model/OrderHistoryBalanceSpecification.scala
  dex/src/test/scala/com/wavesplatform/dex/model/OrderHistoryStub.scala
  dex/src/test/scala/com/wavesplatform/dex/model/OrderValidatorSpecification.scala
  waves-integration/src/main/scala/com/wavesplatform/dex/domain/order/OrderType.scala
Labels: enhancement

#191 DEX-630 Authenticated stream WS unsubscription
  dex-it-common/src/main/scala/com/wavesplatform/dex/it/api/websockets/WebSocketAuthenticatedConnection.scala
  dex-it-common/src/main/scala/com/wavesplatform/dex/it/api/websockets/WebSocketConnection.scala
  dex-test-common/src/main/scala/com/wavesplatform/dex/test/matchers/DiffMatcherWithImplicits.scala
  dex/src/main/scala/com/wavesplatform/dex/AddressActor.scala
  dex/src/main/scala/com/wavesplatform/dex/AddressWsMutableState.scala
  dex/src/test/scala/com/wavesplatform/dex/api/RouteSpec.scala
Labels: enhancement

#197 DEX-644 Save order with rounding issues into Postgres history
  dex-it/src/test/scala/com/wavesplatform/it/sync/PostgresHistoryDatabaseTestSuite.scala
  dex/src/main/scala/com/wavesplatform/dex/AddressDirectory.scala
Labels: bug-fix, version-2.0.x

#198 DEX-656 Timestamp in web socket messages
  dex-it-common/src/main/scala/com/wavesplatform/dex/it/api/websockets/HasWebSockets.scala
  dex-it-common/src/main/scala/com/wavesplatform/dex/it/api/websockets/WebSocketAuthenticatedConnection.scala
  dex-it-common/src/main/scala/com/wavesplatform/dex/it/api/websockets/WebSocketConnection.scala
  dex-it/src/test/scala/com/wavesplatform/it/sync/api/MatcherWebSocketsTestSuite.scala
  dex-test-common/src/main/scala/com/wavesplatform/dex/test/matchers/DiffMatcherWithImplicits.scala
  dex/src/main/scala/com/wavesplatform/dex/api/websockets/WsAddressState.scala
  dex/src/main/scala/com/wavesplatform/dex/api/websockets/WsOrder.scala
  dex/src/main/scala/com/wavesplatform/dex/api/websockets/WsOrderBook.scala
  dex/src/test/scala/com/wavesplatform/dex/api/websockets/WebSocketMessagesSerdeSpecification.scala
Labels: enhancement

#200 DEX-647 Refactor events generated by OrderBook
  dex-it/src/test/scala/com/wavesplatform/it/sync/MatchingRulesTestSuite.scala
  dex-it/src/test/scala/com/wavesplatform/it/sync/api/MatcherWebSocketsTestSuite.scala
  dex-test-common/src/main/scala/com/wavesplatform/dex/test/matchers/DiffMatcherWithImplicits.scala
  dex/src/main/scala/com/wavesplatform/dex/AddressActor.scala
  dex/src/main/scala/com/wavesplatform/dex/AddressDirectory.scala
  dex/src/main/scala/com/wavesplatform/dex/AddressWsMutableState.scala
  dex/src/main/scala/com/wavesplatform/dex/history/HistoryRouter.scala
  dex/src/main/scala/com/wavesplatform/dex/model/MatcherModel.scala
  dex/src/main/scala/com/wavesplatform/dex/model/OrderBook.scala
  dex/src/test/scala/com/wavesplatform/dex/ActorsWebSocketInteractionsSpecification.scala
  dex/src/test/scala/com/wavesplatform/dex/market/OrderBookActorSpecification.scala
  dex/src/test/scala/com/wavesplatform/dex/matching/ReservedBalanceSpecification.scala
  dex/src/test/scala/com/wavesplatform/dex/model/OrderBookSpec.scala
  dex/src/test/scala/com/wavesplatform/dex/model/OrderBookTestSuite.scala
Labels: refactoring

#202 DEX-594 Average weighed price
  dex-it-common/src/main/scala/com/wavesplatform/dex/it/api/responses/dex/OrderBookHistoryItem.scala
  dex-it/src/test/scala/com/wavesplatform/it/sync/OrderHistoryTestSuite.scala
  dex-it/src/test/scala/com/wavesplatform/it/sync/api/MatcherWebSocketsTestSuite.scala
  dex/src/main/scala/com/wavesplatform/dex/AddressActor.scala
  dex/src/main/scala/com/wavesplatform/dex/AddressWsMutableState.scala
  dex/src/main/scala/com/wavesplatform/dex/api/MatcherApiRoute.scala
  dex/src/main/scala/com/wavesplatform/dex/api/websockets/WsOrder.scala
  dex/src/main/scala/com/wavesplatform/dex/model/AcceptedOrderType.scala
  dex/src/main/scala/com/wavesplatform/dex/model/MatcherModel.scala
  dex/src/main/scala/com/wavesplatform/dex/model/OrderBook.scala
  dex/src/main/scala/com/wavesplatform/dex/model/OrderBookSideSnapshot.scala
  dex/src/main/scala/com/wavesplatform/dex/model/OrderBookSnapshot.scala
  dex/src/main/scala/com/wavesplatform/dex/model/OrderInfo.scala
  dex/src/test/scala/com/wavesplatform/dex/ActorsWebSocketInteractionsSpecification.scala
  dex/src/test/scala/com/wavesplatform/dex/AddressActorSpecification.scala
  dex/src/test/scala/com/wavesplatform/dex/MatcherSpecBase.scala
  dex/src/test/scala/com/wavesplatform/dex/api/websockets/WebSocketMessagesSerdeSpecification.scala
  dex/src/test/scala/com/wavesplatform/dex/gen/OrderBookGen.scala
  dex/src/test/scala/com/wavesplatform/dex/market/OrderBookActorSpecification.scala
  dex/src/test/scala/com/wavesplatform/dex/model/OrderBookSpec.scala
  dex/src/test/scala/com/wavesplatform/dex/model/OrderBookTestSuite.scala
  dex/src/test/scala/com/wavesplatform/dex/model/OrderHistoryBalanceSpecification.scala
  dex/src/test/scala/com/wavesplatform/dex/model/OrderInfoSpec.scala
  waves-integration/src/main/scala/com/wavesplatform/dex/domain/order/Order.scala
Labels: enhancement

#206 DEX-666 API key in authenticated WS stream
  dex-it-common/src/main/scala/com/wavesplatform/dex/it/api/websockets/HasWebSockets.scala
  dex-it-common/src/main/scala/com/wavesplatform/dex/it/api/websockets/WebSocketAuthenticatedConnection.scala
  dex-it-common/src/main/scala/com/wavesplatform/dex/it/api/websockets/WebSocketConnection.scala
  dex-it/src/test/scala/com/wavesplatform/it/sync/api/MatcherWebSocketsTestSuite.scala
  dex/src/main/scala/com/wavesplatform/dex/Matcher.scala
  dex/src/main/scala/com/wavesplatform/dex/api/MatcherWebSocketRoute.scala
  dex/src/main/scala/com/wavesplatform/dex/api/http/AuthRoute.scala
  dex/src/main/scala/com/wavesplatform/dex/api/websockets/headers/`X-Error-Code`.scala
  dex/src/main/scala/com/wavesplatform/dex/api/websockets/headers/`X-Error-Message`.scala
  dex/src/main/scala/com/wavesplatform/dex/error/MatcherError.scala
Labels: enhancement

#208 DEX-665 Issued asset balance in WS balance stream
  dex-it-common/src/main/scala/com/wavesplatform/dex/it/waves/MkWavesEntities.scala
  dex-it/src/test/scala/com/wavesplatform/it/sync/api/MatcherWebSocketsTestSuite.scala
  dex-test-common/src/main/scala/com/wavesplatform/dex/asset/DoubleOps.scala
  dex/src/main/resources/application.conf
  dex/src/main/scala/com/wavesplatform/dex/AddressActor.scala
  dex/src/main/scala/com/wavesplatform/dex/AddressWsMutableState.scala
  dex/src/main/scala/com/wavesplatform/dex/Matcher.scala
  dex/src/test/scala/com/wavesplatform/dex/ActorsWebSocketInteractionsSpecification.scala
  dex/src/test/scala/com/wavesplatform/dex/MatcherSpecBase.scala
  dex/src/test/scala/com/wavesplatform/dex/SpendableBalancesActorSpecification.scala
  dex/src/test/scala/com/wavesplatform/dex/grpc/integration/clients/WavesBlockchainClientSpecification.scala
  dex/src/test/scala/com/wavesplatform/dex/matching/ReservedBalanceSpecification.scala
  dex/src/test/scala/com/wavesplatform/dex/settings/BaseSettingsSpecification.scala
  dex/src/test/scala/com/wavesplatform/dex/settings/MatcherSettingsSpecification.scala
  waves-integration-it/src/test/scala/com/wavesplatform/dex/grpc/integration/clients/WavesBlockchainAsyncClientTestSuite.scala
  waves-integration/src/main/scala/com/wavesplatform/dex/grpc/integration/clients/WavesBlockchainClient.scala
  waves-integration/src/main/scala/com/wavesplatform/dex/grpc/integration/clients/WavesBlockchainGrpcAsyncClient.scala
  waves-integration/src/main/scala/com/wavesplatform/dex/grpc/integration/settings/WavesBlockchainClientSettings.scala
Labels: bug-fix

#214 DEX-678 Address actor dedicated settings
  dex-it/src/test/scala/com/wavesplatform/it/sync/MatcherMassOrdersTestSuite.scala
  dex-it/src/test/scala/com/wavesplatform/it/sync/RestOrderLimitTestSuite.scala
  dex-test-common/src/main/scala/com/wavesplatform/dex/test/matchers/DiffMatcherWithImplicits.scala
  dex/src/main/resources/application.conf
  dex/src/main/scala/com/wavesplatform/dex/AddressActor.scala
  dex/src/main/scala/com/wavesplatform/dex/Matcher.scala
  dex/src/main/scala/com/wavesplatform/dex/settings/MatcherSettings.scala
  dex/src/test/scala/com/wavesplatform/dex/settings/BaseSettingsSpecification.scala
  dex/src/test/scala/com/wavesplatform/dex/settings/MatcherSettingsSpecification.scala
Labels: enhancement
