Repository wavesplatform/matcher, pull requests merged in 2020-08, with the labels that each got.

#326 DEX-858 Node 1.2.9 support
  dex-it-common/src/main/scala/com/wavesplatform/dex/it/api/BaseContainersKit.scala
  dex-it-common/src/main/scala/com/wavesplatform/dex/it/docker/WavesNodeContainer.scala
  dex-it/src/test/resources/nodes/waves-base.conf
  dex-it/src/test/scala/com/wavesplatform/it/sync/MultipleMatchersTestSuite.scala
  dex/build.sbt
  project/WavesNodeArtifactsPlugin.scala
  project/plugins.sbt
  waves-ext/build.sbt
  waves-ext/src/main/container/start-matcher-node.sh
  waves-integration-it/build.sbt
  waves-integration-it/src/test/container/start-matcher-node-it.sh
  waves-integration-it/src/test/resources/nodes/waves-base.conf
  waves-integration-it/src/test/scala/com/wavesplatform/dex/grpc/integration/clients/WavesBlockchainAsyncClientTestSuite.scala
  wavesNode.sbt
Labels: enhancement

#325 DEX-852 Zero executed amount in Order Book
  dex-it-common/src/main/scala/com/wavesplatform/dex/it/config/PredefinedAssets.scala
  dex-it/src/test/scala/com/wavesplatform/it/api/ApiExtensions.scala
  dex-it/src/test/scala/com/wavesplatform/it/sync/MatcherTestSuite.scala
  dex-test-common/src/main/scala/com/wavesplatform/dex/asset/DoubleOps.scala
  dex/src/main/scala/com/wavesplatform/dex/model/MatcherModel.scala
  dex/src/main/scala/com/wavesplatform/dex/model/OrderBook.scala
  dex/src/test/scala/com/wavesplatform/dex/MatcherSpecBase.scala
  dex/src/test/scala/com/wavesplatform/dex/model/OrderBookTestSuite.scala
Labels: enhancement

#333 DEX-875 Fixing logs in functional/integration tests
  Jenkinsfile.tests
  Jenkinsfile.tests.kafka
  Jenkinsfile.tests.multiple-versions
  Jenkinsfile.tests.specified-versions
  dex-it-common/src/main/scala/com/wavesplatform/dex/it/docker/DexContainer.scala
  dex-it/build.sbt
  dex/build.sbt
  project/ItTestPlugin.scala
  project/build.properties
Labels: wip

#343 DEX-822 Devnet deployment via Jenkins
  deploy.Jenkinsfile
  dex-load/src/main/resources/reinstallExtension.sh
  dex-load/src/main/resources/reinstallMatcher.sh
  dex-load/src/main/resources/reinstallNode.sh
Labels: wip

#344 DEX-865 Make allure reports nicer
  tests-kafka.Jenkinsfile
  tests-multiple-versions.Jenkinsfile
  tests-specified-versions.Jenkinsfile
  tests.Jenkinsfile
Labels: wip

#349 DEX-893 Column closed_at in orders table
  dex-it/src/test/scala/com/wavesplatform/it/sync/PostgresHistoryDatabaseTestSuite.scala
  dex/src/main/resources/order-history/order-history-ddl.sql
  dex/src/main/scala/com/wavesplatform/dex/Matcher.scala
  dex/src/main/scala/com/wavesplatform/dex/actors/address/AddressDirectoryActor.scala
  dex/src/main/scala/com/wavesplatform/dex/history/DBRecords.scala
  dex/src/main/scala/com/wavesplatform/dex/history/HasPostgresJdbcContext.scala
  dex/src/main/scala/com/wavesplatform/dex/history/HistoryMessagesBatchSenderActor.scala
  dex/src/main/scala/com/wavesplatform/dex/history/HistoryRouter.scala
  dex/src/main/scala/com/wavesplatform/dex/history/HistoryRouterActor.scala
  dex/src/test/scala/com/wavesplatform/dex/history/HistoryRouterActorSpecification.scala
Labels: enhancement

#350 DEX-895 Fix of order status with incomplete execution
  dex-it/src/test/scala/com/wavesplatform/it/sync/PostgresHistoryDatabaseTestSuite.scala
  dex/src/main/scala/com/wavesplatform/dex/history/HistoryMessagesBatchSenderActor.scala
  dex/src/main/scala/com/wavesplatform/dex/history/HistoryRouterActor.scala
  dex/src/main/scala/com/wavesplatform/dex/model/MatcherModel.scala
  dex/src/main/scala/com/wavesplatform/dex/settings/OrderHistorySettings.scala
  dex/src/package/doc/logback.xml
Labels: bug-fix

#351 DEX-729 Update akka-http version to 10.2.0
  dex-jmh/src/test/scala/com/wavesplatform/dex/model/orderbook/OrderBookCancelBenchmark.scala
  dex/src/main/scala/com/wavesplatform/dex/Matcher.scala
  dex/src/main/scala/com/wavesplatform/dex/api/http/routes/MatcherApiRoute.scala
  dex/src/main/scala/com/wavesplatform/dex/api/routes/AuthRoute.scala
  project/Dependencies.scala
Labels: enhancement
