Repository wavesplatform/matcher, pull requests merged in 2020-02, with the labels that each got.

#155 DEX-592 Considering UTX during obtaining of the spendable balance
  dex-it/src/test/scala/com/wavesplatform/it/sync/TradersTestSuite.scala
  waves-ext/src/main/scala/com/wavesplatform/dex/grpc/integration/services/WavesBlockchainApiGrpcService.scala
Labels: bug-fix, version-2.0.x

#154 DEX-565 Basic web socket implementation
  dex-it/src/test/scala/com/wavesplatform/it/sync/api/MatcherWebSocketsTestSuite.scala
  dex/src/main/scala/com/wavesplatform/dex/Matcher.scala
  dex/src/main/scala/com/wavesplatform/dex/api/MatcherWebSocketRoute.scala
Labels: enhancement

#156 DEX-579 Version task sbt plugin
  dex/build.sbt
  project/VersionSourcePlugin.scala
  waves-ext/build.sbt
Labels: enhancement

#158 DEX-593 All assets spendable balance
  dex-it-common/src/main/scala/com/wavesplatform/dex/it/docker/BaseContainer.scala
  dex-it-common/src/main/scala/com/wavesplatform/dex/it/docker/DexContainer.scala
  dex-it-common/src/main/scala/com/wavesplatform/dex/it/docker/WavesNodeContainer.scala
  dex-it-common/src/main/scala/com/wavesplatform/dex/it/waves/MkWavesEntities.scala
  dex/src/main/container/start.sh
  dex/src/test/scala/com/wavesplatform/dex/MatcherSpecBase.scala
  dex/src/test/scala/com/wavesplatform/dex/grpc/integration/clients/WavesBlockchainCachingClientSpecification.scala
  waves-ext/build.sbt
  waves-ext/src/main/scala/com/wavesplatform/dex/grpc/integration/services/WavesBlockchainApiGrpcService.scala
  waves-grpc/src/main/protobuf/waves_blockchain_api.proto
  waves-integration-it/src/test/container/start-waves.sh
  waves-integration-it/src/test/resources/logback-test.xml
  waves-integration-it/src/test/resources/nodes/logback-container.xml
  waves-integration-it/src/test/scala/com/wavesplatform/dex/grpc/integration/clients/WavesBlockchainAsyncClientTestSuite.scala
  waves-integration/src/main/scala/com/wavesplatform/dex/grpc/integration/WavesBlockchainClientBuilder.scala
  waves-integration/src/main/scala/com/wavesplatform/dex/grpc/integration/clients/WavesBlockchainCachingClient.scala
  waves-integration/src/main/scala/com/wavesplatform/dex/grpc/integration/clients/WavesBlockchainClient.scala
  waves-integration/src/main/scala/com/wavesplatform/dex/grpc/integration/clients/WavesBlockchainGrpcAsyncClient.scala
Labels: enhancement

#172 DEX-621 Market order creation fix
  dex-it/src/test/scala/com/wavesplatform/it/sync/MarketOrderTestSuite.scala
  dex/src/main/scala/com/wavesplatform/dex/AddressActor.scala
Labels: bug-fix, version-2.0.x

#174 DEX-616 Log IP of a Node
  dex/src/main/scala/com/wavesplatform/dex/Matcher.scala
  waves-ext/src/main/scala/com/wavesplatform/dex/grpc/integration/services/WavesBlockchainApiGrpcService.scala
  waves-grpc/src/main/protobuf/waves_blockchain_api.proto
  waves-integration/src/main/scala/com/wavesplatform/dex/grpc/integration/clients/WavesBlockchainCachingClient.scala
  waves-integration/src/main/scala/com/wavesplatform/dex/grpc/integration/clients/WavesBlockchainClient.scala
  waves-integration/src/main/scala/com/wavesplatform/dex/grpc/integration/clients/WavesBlockchainGrpcAsyncClient.scala
Labels: enhancement, version-2.0.x

#179 DEX-627 Orders cancelling reproduction test
  dex-it-common/src/main/scala/com/wavesplatform/dex/it/api/HasToxiProxy.scala
  dex-it-common/src/main/scala/com/wavesplatform/dex/it/api/dex/DexApi.scala
  dex-it-common/src/main/scala/com/wavesplatform/dex/it/api/dex/DexApiOps.scala
  dex-it-common/src/main/scala/com/wavesplatform/dex/it/api/dex/HasDex.scala
  dex-it-common/src/main/scala/com/wavesplatform/dex/it/api/node/HasWavesNode.scala
  dex-it/src/test/scala/com/wavesplatform/it/api/ApiExtensions.scala
  dex-it/src/test/scala/com/wavesplatform/it/sync/networking/MultipleMatchersOrderCancelTestSuite.scala
Labels: version-2.0.x
