Repository wavesplatform/matcher, pull requests merged in 2020-07, with the labels that each got.

#308 DEX-814 An accidentally removed subscription
  dex-it/src/test/scala/com/wavesplatform/it/sync/api/ws/WsOrderBookStreamTestSuite.scala
  dex/src/main/scala/com/wavesplatform/dex/OrderBookWsState.scala
  dex/src/main/scala/com/wavesplatform/dex/api/websockets/actors/WsExternalClientHandlerActor.scala
  dex/src/main/scala/com/wavesplatform/dex/api/websockets/connection/TestWsHandlerActor.scala
  dex/src/main/scala/com/wavesplatform/dex/api/websockets/connection/WsConnection.scala
Labels: bug-fix

#309 DEX-814 An accidentally removed subscription
  dex-it/src/test/scala/com/wavesplatform/it/sync/api/ws/WsOrderBookStreamTestSuite.scala
  dex/src/main/scala/com/wavesplatform/dex/api/ws/connection/TestWsHandlerActor.scala
  dex/src/main/scala/com/wavesplatform/dex/api/ws/connection/WsConnection.scala
  dex/src/main/scala/com/wavesplatform/dex/api/ws/state/WsOrderBookState.scala
  dex/src/test/scala/com/wavesplatform/dex/api/http/routes/MatcherApiRouteSpec.scala
Labels: do-not-merge

#310 DEX-816 Address actor fails on unknown asset
  dex-it-common/src/main/scala/com/wavesplatform/dex/it/api/websockets/HasWebSockets.scala
  dex-it/src/test/scala/com/wavesplatform/it/sync/api/ws/WsAddressStreamTestSuite.scala
  dex-it/src/test/scala/com/wavesplatform/it/sync/api/ws/WsInternalStreamTestSuite.scala
  dex/src/main/scala/com/wavesplatform/dex/AddressActor.scala
  dex/src/main/scala/com/wavesplatform/dex/AddressWsMutableState.scala
  dex/src/main/scala/com/wavesplatform/dex/Matcher.scala
  dex/src/main/scala/com/wavesplatform/dex/WavesBlockchainAssetsWatchingClient.scala
  dex/src/main/scala/com/wavesplatform/dex/api/websockets/WsFullOrder.scala
  dex/src/main/scala/com/wavesplatform/dex/api/websockets/WsOrder.scala
  dex/src/main/scala/com/wavesplatform/dex/api/websockets/WsOrdersUpdate.scala
  dex/src/main/scala/com/wavesplatform/dex/db/AssetsStorage.scala
  dex/src/main/scala/com/wavesplatform/dex/error/ErrorFormatterContext.scala
  dex/src/main/scala/com/wavesplatform/dex/error/MatcherError.scala
  dex/src/main/scala/com/wavesplatform/dex/market/OrderBookActor.scala
  dex/src/test/scala/com/wavesplatform/dex/ActorsWebSocketInteractionsSpecification.scala
  dex/src/test/scala/com/wavesplatform/dex/AddressActorSpecification.scala
  dex/src/test/scala/com/wavesplatform/dex/SpendableBalancesActorSpecification.scala
  dex/src/test/scala/com/wavesplatform/dex/api/AggregatedOrderBookActorSpec.scala
  dex/src/test/scala/com/wavesplatform/dex/api/websockets/WsMessagesSerdeSpecification.scala
  dex/src/test/scala/com/wavesplatform/dex/market/MatcherActorSpecification.scala
  dex/src/test/scala/com/wavesplatform/dex/market/OrderBookActorSpecification.scala
  dex/src/test/scala/com/wavesplatform/dex/matching/ReservedBalanceSpecification.scala
  dex/src/test/scala/com/wavesplatform/dex/model/OrderHistoryStub.scala
  dex/src/test/scala/com/wavesplatform/dex/model/OrderValidatorSpecification.scala
  waves-integration/src/main/scala/com/wavesplatform/dex/grpc/integration/WavesBlockchainClientBuilder.scala
  waves-integration/src/main/scala/com/wavesplatform/dex/grpc/integration/clients/WavesBlockchainCachingClient.scala
Labels: bug-fix

#311 DEX-817 Incorrect Waves balance after a WebSocket connection
  dex-it/src/test/scala/com/wavesplatform/it/sync/api/ws/WsAddressStreamTestSuite.scala
  dex/src/main/scala/com/wavesplatform/dex/AddressActor.scala
  waves-ext/src/main/scala/com/wavesplatform/dex/grpc/integration/services/WavesBlockchainApiGrpcService.scala
Labels: bug-fix

#312 DEX-818 Invalid asset balance on connection
  dex-it-common/src/main/scala/com/wavesplatform/dex/it/api/websockets/HasWebSockets.scala
  dex-it-common/src/main/scala/com/wavesplatform/dex/it/docker/WavesNodeContainer.scala
  dex-it/src/test/scala/com/wavesplatform/it/sync/api/ws/WsAddressStreamTestSuite.scala
  dex-it/src/test/scala/com/wavesplatform/it/sync/api/ws/WsOrderBookStreamTestSuite.scala
  dex/src/main/scala/com/wavesplatform/dex/AddressActor.scala
  dex/src/main/scala/com/wavesplatform/dex/AddressWsMutableState.scala
  dex/src/main/scala/com/wavesplatform/dex/SpendableBalancesActor.scala
  dex/src/main/scala/com/wavesplatform/dex/market/AggregatedOrderBookActor.scala
  dex/src/test/scala/com/wavesplatform/dex/AddressActorSpecification.scala
  dex/src/test/scala/com/wavesplatform/dex/SpendableBalancesActorSpecification.scala
  waves-ext/src/main/scala/com/wavesplatform/dex/grpc/integration/services/WavesBlockchainApiGrpcService.scala
Labels: bug-fix

#316 DEX-827 Invalid balances
  dex-it/src/test/scala/com/wavesplatform/it/sync/api/ws/WsAddressStreamTestSuite.scala
  dex/src/main/scala/com/wavesplatform/dex/AddressActor.scala
  dex/src/main/scala/com/wavesplatform/dex/SpendableBalancesActor.scala
  dex/src/test/scala/com/wavesplatform/dex/ActorsWebSocketInteractionsSpecification.scala
Labels: bug-fix

#307 DEX-465 Official Docker Image
  dex-it-common/src/main/scala/com/wavesplatform/dex/it/docker/DexContainer.scala
  dex-it-common/src/main/scala/com/wavesplatform/dex/it/docker/WavesNodeContainer.scala
  dex-it/build.sbt
  dex-it/src/test/container/start-matcher-server-it.sh
  dex/README_DOCKER.md
  dex/build.sbt
  dex/src/main/container/default.conf
  dex/src/main/container/dex.conf
  dex/src/main/container/start-matcher-server.sh
  project/CleanupDanglingImagesPlugin.scala
  project/DexDockerPlugin.scala
  project/DexItDockerPlugin.scala
  project/ImageVersionPlugin.scala
  project/ItCachedArtifactsPlugin.scala
  project/WavesExtensionDockerPlugin.scala
  project/WavesNodeArtifactsPlugin.scala
  project/plugins.sbt
  waves-ext/build.sbt
  waves-ext/src/main/container/start-matcher-node.sh
  waves-ext/src/main/resources/application.conf
  waves-ext/src/package/doc/README.md
  waves-ext/src/package/doc/waves-dex-integration.conf
  waves-integration-it/build.sbt
  waves-integration-it/src/test/container/start-matcher-node-it.sh
  waves-integration/src/main/scala/com/wavesplatform/dex/grpc/integration/settings/GrpcClientSettings.scala
Labels: enhancement

#321 DEX-828 Excess data in WS balance stream
  dex-it/src/test/scala/com/wavesplatform/it/sync/api/ws/WsAddressStreamTestSuite.scala
  dex/src/main/scala/com/wavesplatform/dex/Matcher.scala
  dex/src/main/scala/com/wavesplatform/dex/api/http/routes/MatcherApiRoute.scala
  dex/src/main/scala/com/wavesplatform/dex/error/MatcherError.scala
  dex/src/main/scala/com/wavesplatform/dex/model/OrderValidator.scala
  dex/src/test/scala/com/wavesplatform/dex/model/OrderValidatorSpecification.scala
  waves-ext/src/main/scala/com/wavesplatform/dex/grpc/integration/services/WavesBlockchainApiGrpcService.scala
Labels: bug-fix

#322 DEX-815 AggregatedOrderBookActor scheduling optimization
  dex/src/main/scala/com/wavesplatform/dex/actors/orderbook/AggregatedOrderBookActor.scala
  dex/src/main/scala/com/wavesplatform/dex/api/ws/actors/WsInternalBroadcastActor.scala
Labels: enhancement

#324 DEX-825 AddressActor scheduling optimization
  dex/src/main/scala/com/wavesplatform/dex/actors/address/AddressActor.scala
  project/RunApplicationSettings.scala
Labels: enhancement

#323 DEX-856 Average Weighed Price fix
  dex-it/src/test/scala/com/wavesplatform/it/sync/MatcherTestSuite.scala
  dex/src/main/scala/com/wavesplatform/dex/model/MatcherModel.scala
Labels: bug-fix
