Repository wavesplatform/matcher, pull requests merged in 2020-06, with the labels that each got.

#286 DEX-781 Orders info endpoint fix
  dex-it-common/src/main/scala/com/wavesplatform/dex/it/dex/DexApi.scala
  dex/src/main/scala/com/wavesplatform/dex/api/MatcherApiRoute.scala
  dex/src/test/scala/com/wavesplatform/dex/api/MatcherApiRouteSpec.scala
Labels: bug-fix

#290 DEX-785 Active orders removing during Kafka issues
  dex/src/main/scala/com/wavesplatform/dex/AddressActor.scala
  dex/src/main/scala/com/wavesplatform/dex/AddressWsMutableState.scala
Labels: bug-fix, version-2.1.x

#291 DEX-789 Better error handling due Kafka issues
  dex-it-common/src/main/scala/com/wavesplatform/dex/it/api/HasKafka.scala
  dex-it-common/src/main/scala/com/wavesplatform/dex/it/test/InformativeTestStart.scala
  dex-it/src/test/java/com/wavesplatform/it/tags/DexItExternalKafkaRequired.java
  dex-it/src/test/resources/dex-servers/dex-base.conf
  dex-it/src/test/scala/com/wavesplatform/it/api/ApiExtensions.scala
  dex-it/src/test/scala/com/wavesplatform/it/it.scala
  dex-it/src/test/scala/com/wavesplatform/it/sync/KafkaIssuesTestSuite.scala
  dex-it/src/test/scala/com/wavesplatform/it/sync/MultipleMatchersTestSuite.scala
  dex-it/src/test/scala/com/wavesplatform/it/sync/api/ws/WsPingPongTestSuite.scala
  dex-it/src/test/scala/com/wavesplatform/it/sync/compat/OrderBookBackwardCompatTestSuite.scala
  dex-it/src/test/scala/com/wavesplatform/it/sync/networking/MultipleMatchersOrderCancelTestSuite.scala
  dex/src/main/resources/application.conf
  dex/src/main/scala/com/wavesplatform/dex/AddressActor.scala
  dex/src/main/scala/com/wavesplatform/dex/Matcher.scala
  dex/src/main/scala/com/wavesplatform/dex/api/MatcherApiRoute.scala
  dex/src/main/scala/com/wavesplatform/dex/market/AggregatedOrderBookActor.scala
  dex/src/main/scala/com/wavesplatform/dex/model/OrderBook.scala
  dex/src/main/scala/com/wavesplatform/dex/queue/KafkaMatcherQueue.scala
  dex/src/main/scala/com/wavesplatform/dex/settings/EventsQueueSettings.scala
  dex/src/test/scala/com/wavesplatform/dex/model/OrderBookSpec.scala
  dex/src/test/scala/com/wavesplatform/dex/settings/BaseSettingsSpecification.scala
  dex/src/test/scala/com/wavesplatform/dex/settings/MatcherSettingsSpecification.scala
  project/Dependencies.scala
Labels: bug-fix, version-2.1.x

#295 DEX-782 Matches stream
  dex-it-common/src/main/scala/com/wavesplatform/dex/it/api/websockets/HasJwt.scala
  dex-it-common/src/main/scala/com/wavesplatform/dex/it/api/websockets/HasWebSockets.scala
  dex-it-common/src/main/scala/com/wavesplatform/dex/it/api/websockets/WsMessageOps.scala
  dex-it/src/test/scala/com/wavesplatform/it/WsSuiteBase.scala
  dex-it/src/test/scala/com/wavesplatform/it/api/ApiExtensions.scala
  dex-it/src/test/scala/com/wavesplatform/it/sync/KafkaIssuesTestSuite.scala
  dex-it/src/test/scala/com/wavesplatform/it/sync/api/ws/WsAddressStreamTestSuite.scala
  dex-it/src/test/scala/com/wavesplatform/it/sync/api/ws/WsConnectionTestSuite.scala
  dex-it/src/test/scala/com/wavesplatform/it/sync/api/ws/WsInternalStreamTestSuite.scala
  dex-it/src/test/scala/com/wavesplatform/it/sync/api/ws/WsOrderBookStreamTestSuite.scala
  dex-it/src/test/scala/com/wavesplatform/it/sync/api/ws/WsPingPongBaseSuite.scala
  dex-it/src/test/scala/com/wavesplatform/it/sync/api/ws/WsPingPongExternalTestSuite.scala
  dex-it/src/test/scala/com/wavesplatform/it/sync/api/ws/WsPingPongInternalTestSuite.scala
  dex/src/main/resources/application.conf
  dex/src/main/scala/com/wavesplatform/dex/AddressActor.scala
  dex/src/main/scala/com/wavesplatform/dex/AddressWsMutableState.scala
  dex/src/main/scala/com/wavesplatform/dex/Matcher.scala
  dex/src/main/scala/com/wavesplatform/dex/api/MatcherWebSocketRoute.scala
  dex/src/main/scala/com/wavesplatform/dex/api/websockets/WsFullOrder.scala
  dex/src/main/scala/com/wavesplatform/dex/api/websockets/WsOrder.scala
  dex/src/main/scala/com/wavesplatform/dex/api/websockets/WsOrdersUpdate.scala
  dex/src/main/scala/com/wavesplatform/dex/api/websockets/WsServerMessage.scala
  dex/src/main/scala/com/wavesplatform/dex/api/websockets/actors/WsExternalClientHandlerActor.scala
  dex/src/main/scala/com/wavesplatform/dex/api/websockets/actors/WsHealthCheckSettings.scala
  dex/src/main/scala/com/wavesplatform/dex/api/websockets/actors/WsInternalBroadcastActor.scala
  dex/src/main/scala/com/wavesplatform/dex/api/websockets/actors/WsInternalClientHandlerActor.scala
  dex/src/main/scala/com/wavesplatform/dex/market/CreateExchangeTransactionActor.scala
  dex/src/main/scala/com/wavesplatform/dex/market/ExchangeTransactionBroadcastActor.scala
  dex/src/main/scala/com/wavesplatform/dex/market/MatcherTransactionWriter.scala
  dex/src/main/scala/com/wavesplatform/dex/market/OrderBookActor.scala
  dex/src/main/scala/com/wavesplatform/dex/model/MatcherModel.scala
  dex/src/main/scala/com/wavesplatform/dex/settings/WebSocketSettings.scala
  dex/src/test/scala/com/wavesplatform/dex/ActorsWebSocketInteractionsSpecification.scala
  dex/src/test/scala/com/wavesplatform/dex/AddressActorSpecification.scala
  dex/src/test/scala/com/wavesplatform/dex/api/AggregatedOrderBookActorSpec.scala
  dex/src/test/scala/com/wavesplatform/dex/api/websockets/WsExternalClientHandlerActorSpec.scala
  dex/src/test/scala/com/wavesplatform/dex/api/websockets/WsMessagesSerdeSpecification.scala
  dex/src/test/scala/com/wavesplatform/dex/market/ExchangeTransactionBroadcastActorSpecification.scala
  dex/src/test/scala/com/wavesplatform/dex/market/MatcherActorSpecification.scala
  dex/src/test/scala/com/wavesplatform/dex/market/OrderBookActorSpecification.scala
  dex/src/test/scala/com/wavesplatform/dex/model/OrderHistoryStub.scala
  dex/src/test/scala/com/wavesplatform/dex/settings/BaseSettingsSpecification.scala
  dex/src/test/scala/com/wavesplatform/dex/settings/MatcherSettingsSpecification.scala
Labels: bug-fix, enhancement, version-2.1.x

#297 DEX-774 AvgWeighedPrice fixed for the old OrderInfo versions
  dex/src/main/scala/com/wavesplatform/dex/model/OrderInfo.scala
  dex/src/test/scala/com/wavesplatform/dex/api/http/routes/MatcherApiRouteSpec.scala
Labels: bug-fix

#298 DEX-772 Dependencies bump
  build.sbt
  dex-it-common/src/main/scala/com/wavesplatform/dex/it/docker/BaseContainer.scala
  dex-it/src/test/scala/com/wavesplatform/it/WsSuiteBase.scala
  dex-load/src/main/scala/com/wavesplatform/dex/load/TankGenerator.scala
  dex-load/src/main/scala/com/wavesplatform/dex/load/WavesDexLoadCli.scala
  dex/src/main/scala/com/wavesplatform/dex/Application.scala
  dex/src/main/scala/com/wavesplatform/dex/actors/orderbook/OrderBookActor.scala
  dex/src/main/scala/com/wavesplatform/dex/api/http/routes/MatcherApiRoute.scala
  dex/src/main/scala/com/wavesplatform/dex/metrics/LevelDBStats.scala
  dex/src/main/scala/com/wavesplatform/dex/model/AssetPairBuilder.scala
  dex/src/main/scala/com/wavesplatform/dex/model/OrderValidator.scala
  dex/src/test/scala/com/wavesplatform/dex/MatcherSpecBase.scala
  dex/src/test/scala/com/wavesplatform/dex/api/http/routes/MatcherApiRouteSpec.scala
  project/Dependencies.scala
  project/plugins.sbt
  waves-ext/src/main/scala/com/wavesplatform/dex/grpc/integration/services/WavesBlockchainApiGrpcService.scala
  waves-integration/src/main/scala/com/wavesplatform/dex/grpc/integration/WavesBlockchainClientBuilder.scala
  wavesNode.sbt
Labels: enhancement

#299 DEX-776 Checker improvements
  dex/src/main/scala/com/wavesplatform/dex/cli/WavesDexCli.scala
  dex/src/main/scala/com/wavesplatform/dex/tool/Checker.scala
  dex/src/main/scala/com/wavesplatform/dex/tool/connectors/AuthServiceRestConnector.scala
  dex/src/main/scala/com/wavesplatform/dex/tool/connectors/NodeRestConnector.scala
  dex/src/main/scala/com/wavesplatform/dex/tool/connectors/RestConnector.scala
  dex/src/main/scala/com/wavesplatform/dex/tool/connectors/SuperConnector.scala
Labels: enhancement

#302 DEX-701 Address errors handling in REST API
  dex-it-common/src/main/scala/com/wavesplatform/dex/it/waves/MkWavesEntities.scala
  dex/src/main/scala/com/wavesplatform/dex/api/http/entities/MatcherResponse.scala
  dex/src/main/scala/com/wavesplatform/dex/api/http/routes/MatcherApiRoute.scala
  dex/src/main/scala/com/wavesplatform/dex/api/routes/PathMatchers.scala
  dex/src/main/scala/com/wavesplatform/dex/error/MatcherError.scala
  dex/src/test/scala/com/wavesplatform/dex/api/http/routes/MatcherApiRouteSpec.scala
  waves-integration/src/main/scala/com/wavesplatform/dex/domain/account/Address.scala
Labels: enhancement

#303 DEX-728 Order version in OrderInfo
  dex-it/src/test/scala/com/wavesplatform/it/sync/MatcherTestSuite.scala
  dex/src/main/scala/com/wavesplatform/dex/actors/address/AddressActor.scala
  dex/src/main/scala/com/wavesplatform/dex/api/http/entities/HttpOrderBookHistoryItem.scala
  dex/src/main/scala/com/wavesplatform/dex/model/OrderInfo.scala
  dex/src/test/scala/com/wavesplatform/dex/api/http/entities/HttpOrderBookHistoryItemSpec.scala
  dex/src/test/scala/com/wavesplatform/dex/api/http/routes/MatcherApiRouteSpec.scala
  dex/src/test/scala/com/wavesplatform/dex/model/OrderInfoSpec.scala
Labels: enhancement

#305 DEX-799 Merge version-2.0.x into master
  dex-it-common/src/main/scala/com/wavesplatform/dex/it/api/HasKafka.scala
  dex-it-common/src/main/scala/com/wavesplatform/dex/it/api/node/HasWavesNode.scala
  dex-it-common/src/main/scala/com/wavesplatform/dex/it/api/websockets/HasJwt.scala
  dex-it-common/src/main/scala/com/wavesplatform/dex/it/api/websockets/HasWebSockets.scala
  dex-it-common/src/main/scala/com/wavesplatform/dex/it/api/websockets/WsMessageOps.scala
  dex-it-common/src/main/scala/com/wavesplatform/dex/it/dex/HasDex.scala
  dex-it-common/src/main/scala/com/wavesplatform/dex/it/test/InformativeTestStart.scala
  dex-it/src/test/java/com/wavesplatform/it/tags/DexItExternalKafkaRequired.java
  dex-it/src/test/resources/dex-servers/dex-base.conf
  dex-it/src/test/scala/com/wavesplatform/it/WsSuiteBase.scala
  dex-it/src/test/scala/com/wavesplatform/it/api/ApiExtensions.scala
  dex-it/src/test/scala/com/wavesplatform/it/it.scala
  dex-it/src/test/scala/com/wavesplatform/it/sync/KafkaIssuesTestSuite.scala
  dex-it/src/test/scala/com/wavesplatform/it/sync/MultipleMatchersTestSuite.scala
  dex-it/src/test/scala/com/wavesplatform/it/sync/api/ws/WsAddressStreamTestSuite.scala
  dex-it/src/test/scala/com/wavesplatform/it/sync/api/ws/WsConnectionTestSuite.scala
  dex-it/src/test/scala/com/wavesplatform/it/sync/api/ws/WsInternalStreamTestSuite.scala
  dex-it/src/test/scala/com/wavesplatform/it/sync/api/ws/WsOrderBookStreamTestSuite.scala
  dex-it/src/test/scala/com/wavesplatform/it/sync/api/ws/WsPingPongBaseSuite.scala
  dex-it/src/test/scala/com/wavesplatform/it/sync/api/ws/WsPingPongExternalTestSuite.scala
  dex-it/src/test/scala/com/wavesplatform/it/sync/api/ws/WsPingPongInternalTestSuite.scala
  dex-it/src/test/scala/com/wavesplatform/it/sync/compat/OrderBookBackwardCompatTestSuite.scala
  dex-it/src/test/scala/com/wavesplatform/it/sync/networking/MultipleMatchersOrderCancelTestSuite.scala
  dex/src/main/resources/application.conf
  dex/src/main/scala/com/wavesplatform/dex/Matcher.scala
  dex/src/main/scala/com/wavesplatform/dex/actors/address/AddressActor.scala
  dex/src/main/scala/com/wavesplatform/dex/actors/orderbook/AggregatedOrderBookActor.scala
  dex/src/main/scala/com/wavesplatform/dex/actors/orderbook/OrderBookActor.scala
  dex/src/main/scala/com/wavesplatform/dex/actors/tx/BroadcastExchangeTransactionActor.scala
  dex/src/main/scala/com/wavesplatform/dex/actors/tx/CreateExchangeTransactionActor.scala
  dex/src/main/scala/com/wavesplatform/dex/actors/tx/WriteExchangeTransactionActor.scala
  dex/src/main/scala/com/wavesplatform/dex/api/http/routes/MatcherApiRoute.scala
  dex/src/main/scala/com/wavesplatform/dex/api/ws/actors/WsExternalClientHandlerActor.scala
  dex/src/main/scala/com/wavesplatform/dex/api/ws/actors/WsHealthCheckSettings.scala
  dex/src/main/scala/com/wavesplatform/dex/api/ws/actors/WsInternalBroadcastActor.scala
  dex/src/main/scala/com/wavesplatform/dex/api/ws/actors/WsInternalClientHandlerActor.scala
  dex/src/main/scala/com/wavesplatform/dex/api/ws/entities/WsFullOrder.scala
  dex/src/main/scala/com/wavesplatform/dex/api/ws/entities/WsOrder.scala
  dex/src/main/scala/com/wavesplatform/dex/api/ws/protocol/WsOrdersUpdate.scala
  dex/src/main/scala/com/wavesplatform/dex/api/ws/protocol/WsServerMessage.scala
  dex/src/main/scala/com/wavesplatform/dex/api/ws/routes/MatcherWebSocketRoute.scala
  dex/src/main/scala/com/wavesplatform/dex/api/ws/state/WsAddressState.scala
  dex/src/main/scala/com/wavesplatform/dex/model/MatcherModel.scala
  dex/src/main/scala/com/wavesplatform/dex/model/OrderBook.scala
  dex/src/main/scala/com/wavesplatform/dex/queue/KafkaMatcherQueue.scala
  dex/src/main/scala/com/wavesplatform/dex/settings/EventsQueueSettings.scala
  dex/src/main/scala/com/wavesplatform/dex/settings/WebSocketSettings.scala
  dex/src/test/resources/logback-test.xml
  dex/src/test/scala/com/wavesplatform/dex/actors/MatcherActorSpecification.scala
  dex/src/test/scala/com/wavesplatform/dex/actors/address/AddressActorSpecification.scala
  dex/src/test/scala/com/wavesplatform/dex/actors/orderbook/AggregatedOrderBookActorSpec.scala
  dex/src/test/scala/com/wavesplatform/dex/actors/orderbook/OrderBookActorSpecification.scala
  dex/src/test/scala/com/wavesplatform/dex/actors/tx/BroadcastExchangeTransactionActorSpecification.scala
  dex/src/test/scala/com/wavesplatform/dex/api/ws/ActorsWebSocketInteractionsSpecification.scala
  dex/src/test/scala/com/wavesplatform/dex/api/ws/WsMessagesSerdeSpecification.scala
  dex/src/test/scala/com/wavesplatform/dex/api/ws/actors/WsExternalClientHandlerActorSpec.scala
  dex/src/test/scala/com/wavesplatform/dex/model/OrderBookSpec.scala
  dex/src/test/scala/com/wavesplatform/dex/model/OrderHistoryStub.scala
  dex/src/test/scala/com/wavesplatform/dex/settings/BaseSettingsSpecification.scala
  dex/src/test/scala/com/wavesplatform/dex/settings/MatcherSettingsSpecification.scala
Labels: do-not-merge

#304 DEX-712 Last Trade in Order Book update results
  dex-jmh/src/test/scala/com/wavesplatform/dex/model/orderbook/OrderBookAddBenchmark.scala
  dex/src/main/scala/com/wavesplatform/dex/actors/orderbook/OrderBookActor.scala
  dex/src/main/scala/com/wavesplatform/dex/model/OrderBook.scala
  dex/src/test/resources/logback-test.xml
  dex/src/test/scala/com/wavesplatform/dex/actors/orderbook/OrderBookActorSpecification.scala
  dex/src/test/scala/com/wavesplatform/dex/model/OrderBookSpec.scala
  dex/src/test/scala/com/wavesplatform/dex/model/OrderBookTestSuite.scala
  release-notes.md
Labels: enhancement
